const menuSeedItems = [
  { name: "Combo Nướng Khởi Đầu", price: 359, type: "COMBO" },
  { name: "Combo Nướng Vui Vẻ", price: 499, type: "COMBO" },
  { name: "Xúc xích nướng", price: 59, type: "FOOD" },
  { name: "Xúc xích chiên", price: 69, type: "FOOD" },
  { name: "Khoai tây chiên", price: 69, type: "FOOD" },
  { name: "Khoai tây lắc phô mai", price: 79, type: "FOOD" },
  { name: "Salad trứng", price: 89, type: "FOOD" },
  { name: "Salad chanh dây", price: 99, type: "FOOD" },
  { name: "Salad lươn ngồng", price: 129, type: "FOOD" },
  { name: "Ốc nhồi thịt", price: 169, type: "FOOD" },
  { name: "Ốc nhồi ống nửa", price: 169, type: "FOOD" },
  { name: "Heo mọi/Nai xông đá núi", price: 259, type: "FOOD" },
  { name: "Heo mọi/Nai xào sả ớt", price: 219, type: "FOOD" },
  { name: "Bò tảng đất vàng", price: 229, type: "FOOD" },
  { name: "Gà nướng sốt tiêu xanh", price: 409, type: "FOOD" },
  { name: "Sụn gà chiên mắm", price: 149, type: "FOOD" },
  { name: "Chân gà chiên mắm", price: 149, type: "FOOD" },
  { name: "Cánh gà chiên mắm", price: 149, type: "FOOD" },
  { name: "Ếch chiên giòn", price: 169, type: "FOOD" },
  { name: "Cá trứng chiên giòn", price: 179, type: "FOOD" },
  { name: "Rau muống xào tỏi", price: 99, type: "FOOD" },
  { name: "Rau củ xào chay", price: 99, type: "FOOD" },
  { name: "Rau rừng xào tỏi", price: 109, type: "FOOD" },
  { name: "Măng tây xào tỏi", price: 119, type: "FOOD" },
  { name: "Rau muống xào bò", price: 119, type: "FOOD" },
  { name: "Măng tây xào bò", price: 149, type: "FOOD" },
  { name: "Lẩu cá tầm măng chua (nhỏ)", price: 259, type: "FOOD" },
  { name: "Lẩu cá tầm măng chua (lớn)", price: 389, type: "FOOD" },
  { name: "Lẩu gà lá é (nhỏ)", price: 239, type: "FOOD" },
  { name: "Lẩu gà lá é (lớn)", price: 369, type: "FOOD" },
  { name: "Lẩu Thái Tomyum (nhỏ)", price: 269, type: "FOOD" },
  { name: "Lẩu Thái Tomyum (lớn)", price: 369, type: "FOOD" },
  { name: "Lẩu sườn thập cẩm (nhỏ)", price: 499, type: "FOOD" },
  { name: "Lẩu sườn thập cẩm (lớn)", price: 599, type: "FOOD" },
  { name: "Nấm kim châm", price: 30, type: "FOOD" },
  { name: "Mì gói", price: 10, type: "FOOD" },
  { name: "Bún", price: 12, type: "FOOD" },
  { name: "Rau lẩu", price: 40, type: "FOOD" },
  { name: "Dĩa lẩu Thái (nhỏ)", price: 159, type: "FOOD" },
  { name: "Dĩa lẩu Thái (lớn)", price: 199, type: "FOOD" },
  { name: "Dĩa lẩu gà lá é (nhỏ)", price: 139, type: "FOOD" },
  { name: "Dĩa lẩu gà lá é (lớn)", price: 179, type: "FOOD" },
  { name: "Dĩa lẩu cá tầm + rau", price: 229, type: "FOOD" },
  { name: "Cơm lam", price: 30, type: "FOOD" },
  { name: "Chân gà nướng", price: 129, type: "FOOD" },
  { name: "Cánh gà nướng sate/muối ớt", price: 149, type: "FOOD" },
  { name: "Cánh gà nướng sốt BBQ", price: 149, type: "FOOD" },
  { name: "Gà nướng (1/2 con)", price: 219, type: "FOOD" },
  { name: "Gà nướng (1 con)", price: 379, type: "FOOD" },
  { name: "Ba chỉ bò nướng sate", price: 189, type: "FOOD" },
  { name: "Ba chỉ bò nướng muối ớt", price: 189, type: "FOOD" },
  { name: "Ba chỉ bò cuộn kim châm", price: 189, type: "FOOD" },
  { name: "Ba chỉ bò cuộn măng tây", price: 199, type: "FOOD" },
  { name: "Ba chỉ bò cuộn phô mai", price: 199, type: "FOOD" },
  { name: "Bò tảng nướng BBQ", price: 209, type: "FOOD" },
  { name: "Bò tảng nướng sate", price: 209, type: "FOOD" },
  { name: "Bò tảng nướng muối ớt", price: 209, type: "FOOD" },
  { name: "Bò tảng nướng sốt phô mai", price: 219, type: "FOOD" },
  { name: "Bò tảng nướng Hoàng Kim", price: 219, type: "FOOD" },
  { name: "Đùi ếch nướng sate", price: 179, type: "FOOD" },
  { name: "Đùi ếch nướng muối ớt", price: 179, type: "FOOD" },
  { name: "Đùi ếch nướng tiêu xanh", price: 179, type: "FOOD" },
  { name: "Đùi ếch nướng BBQ", price: 179, type: "FOOD" },
  { name: "Ếch xào sả ớt", price: 189, type: "FOOD" },
  { name: "Cá trứng nướng muối ớt", price: 169, type: "FOOD" },
  { name: "Cá trứng nướng sate", price: 169, type: "FOOD" },
  { name: "Cá trứng nướng tiêu xanh", price: 169, type: "FOOD" },
  { name: "Cá tầm nướng muối ớt", price: 209, type: "FOOD" },
  { name: "Cá tầm nướng sate", price: 209, type: "FOOD" },
  { name: "Cá tầm nướng tiêu xanh", price: 209, type: "FOOD" },
  { name: "Sò điệp nhật nướng phô mai", price: 179, type: "FOOD" },
  { name: "Sò điệp nhật nướng mỡ hành", price: 179, type: "FOOD" },
  { name: "Sò điệp nhật nướng tiêu xanh", price: 179, type: "FOOD" },
  { name: "Sò điệp nhật nướng sate", price: 179, type: "FOOD" },
  { name: "Lươn ngồng nướng sốt tiêu", price: 139, type: "FOOD" },
  { name: "Lươn ngồng nướng muối ớt", price: 139, type: "FOOD" },
  { name: "Lươn ngồng nướng sa tế", price: 139, type: "FOOD" },
  { name: "Lươn ngồng sốt chanh dây", price: 159, type: "FOOD" },
  { name: "Ba chỉ heo nướng sate", price: 159, type: "FOOD" },
  { name: "Ba chỉ heo nướng muối ớt", price: 159, type: "FOOD" },
  { name: "Phần dưới bụng heo (nầm) nướng", price: 159, type: "FOOD" },
  { name: "Sườn heo nướng BBQ", price: 169, type: "FOOD" },
  { name: "Heo mọi/Nai nướng muối ớt/sa tế", price: 169, type: "FOOD" },
  { name: "Tôm nướng sate", price: 169, type: "FOOD" },
  { name: "Tôm nướng muối ớt", price: 169, type: "FOOD" },
  { name: "Bạch tuộc nướng sate", price: 169, type: "FOOD" },
  { name: "Bạch tuộc nướng muối ớt", price: 169, type: "FOOD" },
  { name: "Râu bạch tuộc khổng lồ nướng", price: 169, type: "FOOD" },
  { name: "Mực nướng muối ớt", price: 199, type: "FOOD" },
  { name: "Mực nướng sate", price: 199, type: "FOOD" },
  { name: "Cơm chiên trứng", price: 89, type: "FOOD" },
  { name: "Mì xào rau củ", price: 99, type: "FOOD" },
  { name: "Mì xào bò", price: 119, type: "FOOD" },
  { name: "Mì xào hải sản", price: 129, type: "FOOD" },
  { name: "Cơm chiên Dương Châu", price: 129, type: "FOOD" },
  { name: "Cơm chiên hải sản", price: 139, type: "FOOD" },
  { name: "Kim chi", price: 30, type: "FOOD" },
  { name: "Rau đổ nướng", price: 20, type: "FOOD" },
  { name: "Sốt phô mai/Hoàng Kim", price: 30, type: "FOOD" },
  { name: "Nước suối", price: 12, type: "DRINK" },
  { name: "Nước ngọt (Pepsi/7Up/Sting)", price: 20, type: "DRINK" },
  { name: "Trà tắc / Trà chanh", price: 20, type: "DRINK" },
  { name: "Nước cam vắt", price: 35, type: "DRINK" },
  { name: "Nước ép dưa hấu", price: 35, type: "DRINK" },
  { name: "Nước ép cà rốt", price: 35, type: "DRINK" },
  { name: "Bia lon SG Lager", price: 20, type: "DRINK" },
  { name: "Bia lon SG Chill", price: 25, type: "DRINK" },
  { name: "Bia lon Tiger nâu", price: 25, type: "DRINK" },
  { name: "Bia lon Tiger bạc", price: 28, type: "DRINK" },
  { name: "Bia lon Heineken bạc", price: 30, type: "DRINK" },
  { name: "Rượu mơ/má đào/táo mèo (250ml)", price: 109, type: "DRINK" },
  { name: "Rượu mơ/má đào/táo mèo (500ml)", price: 189, type: "DRINK" },
  { name: "Rượu Atiso (500ml)", price: 99, type: "DRINK" },
  { name: "Rượu Soju", price: 119, type: "DRINK" },
];

module.exports = { menuSeedItems };
